# These are supported funding model platforms

github: # fahadansari9326
patreon: # fahadansari9326
open_collective: # fahadansari9326
ko_fi: # fahadansari9326
tidelift: # salahtime
community_bridge: # salahtime
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: # salahtime
polar: # fahadansari9326
buy_me_a_coffee: # Replace with a single Buy Me a Coffee fahadansari9326
thanks_dev: # Replace with a single thanks.dev fahadansari9326
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
